In [29]:
import numpy as np
import pandas as pd
import matplotlib.pyplot as plt
from IPython.display import Image as IPImage
import scipy.ndimage as ndimage
from scipy import signal, misc
from skimage import feature
import math

In [2]:
def showImage(im):
    plt.clf()
    plt.imshow(im)
    plt.show()

In [114]:
filename = 'colorful3_threshold.jpg'
name = 'mooncraters'
r = 40

In [115]:
image = misc.imread(filename)

In [116]:
a = 23.7
int(a)

23

In [117]:
def hough(im):
    hough_bins = np.zeros((im.shape[0] / 10 + 1, im.shape[1] / 10 + 1))
    for x in range(im.shape[0]):
        for y in range(im.shape[1]):
            if im[x,y] == 255:
                for x0 in range(im.shape[0]):
                    if r*r - (x-x0)*(x-x0) < 0:
                        continue
                    y0 = y - math.sqrt(r*r - (x-x0)*(x-x0))
                    hough_bins[x0 / 10 - 1, int(y0) / 10 - 1] = hough_bins[x0 / 10 - 1, int(y0) / 10 - 1] + 1
    return hough_bins

In [118]:
hb = hough(image)
hb

array([[ 434.,  282.,  224., ...,  443.,  527.,  512.],
       [ 637.,  358.,  250., ...,  441.,  589.,  620.],
       [ 700.,  516.,  329., ...,  542.,  617.,  726.],
       ..., 
       [ 387.,  327.,  149., ...,  289.,  288.,  451.],
       [ 176.,  143.,   57., ...,  113.,   90.,  171.],
       [ 325.,  314.,  138., ...,  325.,  463.,  481.]])

In [119]:
hb.max()

1363.0

In [120]:
np.where(hb == 690)[0][0]

25

In [121]:
np.where(hb == 84)

(array([], dtype=int64), array([], dtype=int64))

In [125]:
hb2 = np.copy(hb)
plt.clf()
plt.imshow(image)
for x in range(2):
    loc = np.where(hb2 == hb2.max())
    print loc
    circle1 = plt.Circle((loc[0][0]*10 + 5, loc[1][0]*10 + 5),r,color='y',fill=0)
    plt.gca().add_artist(circle1)
    hb2[loc[0][0], loc[1][0]] = 0
plt.show()

(array([19]), array([9]))
(array([18]), array([8]))


In [41]:
ind = np.argpartition(hb, -4)[-4:]
ind
# a[ind]

array([[17, 25, 50,  3,  4,  5, 46, 41, 30, 28, 26, 24, 22, 13, 18, 51, 40,
        33, 14, 19, 20, 21, 12,  2, 11,  1, 10, 49,  9, 29, 48, 47,  6, 44,
        34, 42, 36, 37, 38, 39, 16, 23,  0, 32,  8,  7, 15, 27, 43, 35, 31,
        45],
       [17, 25, 41, 36,  4,  5, 30, 29, 24,  9, 22, 11, 21, 13, 14, 19, 18,
         0, 39, 51, 20, 12, 10, 50, 49,  1, 26, 48, 28, 47,  6, 46, 43, 33,
         2, 35,  3, 40, 34, 38, 44, 31, 23,  7,  8, 27, 32, 37, 42, 15, 45,
        16],
       [14, 25, 49, 44, 41, 37, 36, 30, 23, 22, 19, 18, 17,  0, 40, 13, 50,
        12, 11, 10, 20, 21,  9,  8, 24,  1, 26, 27, 28, 29,  2, 31, 47, 33,
        34,  3,  6,  5, 38,  4, 51, 48, 46, 43, 35, 39, 42, 32, 15, 45, 16,
         7],
       [21,  0,  2, 39, 37,  5,  6,  7,  8, 36, 10, 35, 12, 30,  1, 51, 32,
        16, 48, 19, 20, 45, 22, 23, 24, 14, 44,  3, 38, 17, 13, 25, 47, 41,
        50, 11, 18,  4, 28, 27, 40, 29, 42, 43, 26, 15, 46, 33,  9, 31, 34,
        49]])